collections:
  authors:
    output: true
  publishers:
    output: true
  critics:
    output: true
  categories:
    output: true
  tags:
    output: true
defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "publishers"
    values:
      layout: "publisher"
  - scope:
      path: ""
      type: "critics"
    values:
      layout: "critic"
  - scope:
      path: ""
      type: "categories"
    values:
      layout: "category"
  - scope:
      path: ""
      type: "tags"
    values:
      layout: "tag"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
