title: نیم‌فاصله
permalink: /:categories/:title/
gems: [jekyll/imgix]
imgix:
  source: assets.imgix.net # Your imgix source address
  secure_url_token: FACEBEEF12 # (optional) The Secure URL Token associated with your source
  include_library_param: true  # (optional) If `true` all the URLs will include `ixlib` parameter
collections:
  authors:
    output: true
  publishers:
    output: true
  reviewers:
    output: true
  categories:
    output: true
    permalink: /:name
  tags:
    output: true
defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "publishers"
    values:
      layout: "publisher"
  - scope:
      path: ""
      type: "reviewers"
    values:
      layout: "reviewer"
  - scope:
      path: ""
      type: "categories"
    values:
      layout: "category"
  - scope:
      path: ""
      type: "tags"
    values:
      layout: "tag"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
