mini_magick:
    thumbnail:
        source: images/originals
        destination: images/thumbnail
        resize: "100x70^"
        gravity: "center"
        extent: "100x70"
title: نیم‌فاصله
permalink: /:categories/:title/
collections:
  authors:
    output: true
  publishers:
    output: true
  reviewers:
    output: true
  categories:
    output: true
    permalink: /:name
  tags:
    output: true
defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "publishers"
    values:
      layout: "publisher"
  - scope:
      path: ""
      type: "reviewers"
    values:
      layout: "reviewer"
  - scope:
      path: ""
      type: "categories"
    values:
      layout: "category"
  - scope:
      path: ""
      type: "tags"
    values:
      layout: "tag"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
